export default {
    THEME_CHANGE: 'THEME_CHANGE',
    THEME_INIT: 'THEME_INIT',

    //最热页面
    POPULAR_DROPDOWN_REFRESH: 'POPULAR_DROPDOWN_REFRESH',
    POPULAR_DROPDOWN_REFRESH_FAIL: 'POPULAR_DROPDOWN_REFRESH_FAIL',
    POPULAR_DROPDOWN_REFRESH_SUCCESS: 'POPULAR_DROPDOWN_REFRESH_SUCCESS',
    POPULAR_LOAD_MORE_FAIL: "POPULAR_LOAD_MORE_FAIL",
    POPULAR_LOAD_MORE_SUCCESS: "POPULAR_LOAD_MORE_SUCCESS",

    //趋势页面
    TRENDING_REFRESH: 'TRENDING_REFRESH',
    TRENDING_REFRESH_FAIL: 'TRENDING_REFRESH_FAIL',
    TRENDING_REFRESH_SUCCESS: 'TRENDING_REFRESH_SUCCESS',
    TRENDING_LOAD_MORE_SUCCESS: 'TRENDING_LOAD_MORE_SUCCESS',
    TRENDING_LOAD_MORE_FAIL: 'TRENDING_LOAD_MORE_FAIL',
}